FROM python:3.8

WORKDIR /usr/src/BaMMI

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

COPY ./BaMMI/utils ./BaMMI/utils/
COPY ./BaMMI/parsers ./BaMMI/parsers/

CMD ["./run_parsers.sh"]
