FROM python:3.8

WORKDIR /usr/src/BaMMI

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./BaMMI/utils ./BaMMI/utils/
COPY ./BaMMI/saver ./BaMMI/saver/

CMD ["python", "-m", "BaMMI.saver", "run-saver", "mongodb://127.0.0.1:27017/", "rabbitmq://127.0.0.1:5672"]
