FROM python:3.8

WORKDIR /usr/src/BaMMI

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

COPY ./BaMMI/utils ./BaMMI/utils/
COPY ./BaMMI/server ./BaMMI/server/

CMD ["python", "-m", "BaMMI.server", '-t', "run-server", "-h", "0.0.0.0"]
