FROM python:3.8

WORKDIR /usr/src/BaMMI

COPY ../requirements.txt ./
RUN pip install -r requirements.txt

COPY ../BaMMI_pb2.py ./
COPY Receiver.py ./APIServer.py ./PubSuber.py ./ServerSide/

CMD ["python", "./Reciever.py"]
